name: py3.9

on:
  push:
    branches:
      - main
#  pull_request:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # Conditional step to install libomp on macOS
    # Need libomp on macOS to run XGBoost
    - name: Install libomp on macOS
      if: matrix.os == 'macos-latest'
      run: brew install libomp

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies with Poetry
      run: |
        poetry lock
        poetry install

    - name: Run tests
      run: |
        poetry run pytest tests/ --doctest-modules -v --maxfail=1 --disable-warnings
      timeout-minutes: 120
